"use client";

import { useCallback, useEffect, useState } from "react";

import { getSummary, type SituationSummary } from "../lib/api";

const PHASE_COLOR: Record<string, string> = {
  lateral_movement: "#b8860b", discovery: "#6a4ca8", execution: "#0f8a63", command_and_control: "#c0392b",
};
const REASON_COLOR: Record<string, string> = {
  auth_anomaly: "#1f5fb0", net_anomaly: "#0f8a63", discovery: "#6a4ca8",
  process_corroborated: "#b8860b", external_corroborated: "#c0392b",
};

function Bars({ title, data }: { title: string; data: [string, number, string][] }) {
  const max = Math.max(1, ...data.map(([, v]) => v));
  return (
    <div className="rep-chart">
      <div className="rep-chart-title">{title}</div>
      {data.map(([k, v, color]) => (
        <div key={k} className="rep-bar">
          <span className="rbk">{k}</span>
          <span className="rbt"><span className="rbf" style={{ width: `${(v / max) * 100}%`, background: color }} /></span>
          <span className="rbn">{v}</span>
        </div>
      ))}
    </div>
  );
}

export function SummaryReport() {
  const [s, setS] = useState<SituationSummary | null>(null);
  const [busy, setBusy] = useState(false);
  const load = useCallback((refresh = false) => getSummary(refresh).then(setS).catch(() => {}), []);

  useEffect(() => {
    load();
    // poll a few times while the narrative generates in the background
    let n = 0;
    const t = setInterval(() => {
      setS((cur) => {
        if (cur && (cur.narrative || cur.error) && !cur.generating) { clearInterval(t); }
        return cur;
      });
      if (++n > 12) clearInterval(t);
      load();
    }, 2500);
    return () => clearInterval(t);
  }, [load]);

  const regen = async () => { setBusy(true); try { await load(true); } finally { setBusy(false); } };

  const d = s?.digest;
  const phase = d ? (Object.entries(d.phase_counts) as [string, number][])
    .map(([k, v]) => [k.replace(/_/g, " "), v, PHASE_COLOR[k]] as [string, number, string]) : [];
  const reasons = d ? (Object.entries(d.flag_reasons) as [string, number][])
    .map(([k, v]) => [k.replace(/_/g, " "), v, REASON_COLOR[k]] as [string, number, string]) : [];
  const resp = d ? [
    ["pending", d.response.pending, "#b8860b"], ["executed", d.response.executed, "#0f8a63"],
    ["failed", d.response.failed, "#c0392b"], ["reverted", d.response.reverted, "#555"],
  ] as [string, number, string][] : [];

  return (
    <section>
      <div className="rep-summary-head">
        <h2>1 · Situation summary</h2>
        <button type="button" className="rep-regen no-print" onClick={regen} disabled={busy}>
          {busy ? "regenerating…" : "↻ regenerate"}
        </button>
      </div>

      <div className="rep-narrative">
        {s?.narrative ? (
          <p>{s.narrative}</p>
        ) : s?.error ? (
          <p className="rep-muted">AI narrative unavailable — {s.error}. Charts below are computed locally and remain accurate.</p>
        ) : (
          <p className="rep-muted">Generating analyst summary from the local model…</p>
        )}
        {s && (
          <div className="rep-byline">
            {s.narrative ? `Generated by ${s.model}${s.generated_at ? ` · ${s.generated_at.replace("T", " ").slice(0, 19)} UTC` : ""}${s.stale ? " · refreshing" : ""}` : ""}
          </div>
        )}
      </div>

      {d && (
        <>
          <table className="rep-posture">
            <tbody>
              <tr>
                <th>Mode</th><td>{d.mode}{d.baseline_ready ? " · baseline frozen" : ""}</td>
                <th>Sensors</th><td>{d.hosts_online}/{d.hosts} online</td>
                <th>Events seen</th><td>{d.events_seen.toLocaleString()}</td>
              </tr>
              <tr>
                <th>Flagged (window)</th><td>{d.flagged_recent}</td>
                <th>Incidents</th><td>{d.incident_count} · {d.high_confidence_count} high-confidence</td>
                <th>Actions</th><td>{d.response.pending} pending · {d.response.executed} executed</td>
              </tr>
            </tbody>
          </table>

          <div className="rep-charts">
            <Bars title="Kill-chain phases (flagged)" data={phase} />
            <Bars title="Why events were flagged" data={reasons} />
            <Bars title="Response actions" data={resp} />
          </div>

          {d.top_incidents.length > 0 && (
            <div className="rep-chart">
              <div className="rep-chart-title">Top incidents by compound risk</div>
              {d.top_incidents.map((i) => (
                <div key={i.id} className="rep-bar">
                  <span className="rbk">{i.entity}{i.high_confidence ? " ●" : ""}</span>
                  <span className="rbt"><span className="rbf" style={{ width: `${i.score * 100}%`, background: i.high_confidence ? "#c0392b" : "#b8860b" }} /></span>
                  <span className="rbn">{i.score.toFixed(2)}</span>
                </div>
              ))}
            </div>
          )}
        </>
      )}
    </section>
  );
}
